name: Lastpiece
version: '0.0-Alpha'
main: org.me.lastpiece.Lastpiece
api-version: '1.21'

commands:
  editManaCap:
    description: Edit a player's Mana Cap
    usage: /editManaCap <Player> <New Cap>
    permission: Lastpiece.ManaClearance
    aliases:
      - manaCap
  editPlayerMana:
    description: Edit a player's Mana by certain Amount
    usage: /editPlayerMana <Player> <Edit Amount>
    permission: Lastpiece.ManaClearance
    aliases:
      - newMana
  getBoomWand:
    description: Gives a player the Boom Wand.
    usage: /getBoomWand <Player>
    permission: Lastpiece.ExoticItemClearance
    aliases:
      - giveBoomWand

permissions:
  Lastpiece.ManaClearance:
    description: Allows some players to affect mana.
    default: op

  Lastpiece.ExoticItemClearance:
    description: Allows some players to use exotic items.
    default: op